services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Public services
    Phillarmonic\AllegroRedisOdmBundle\DocumentManager:
        alias: 'allegro_redis_odm.document_manager'
        public: true

    # The Redis client will be configured by the extension based on configuration
    allegro_redis_odm.client:
        class: Redis  # This will be replaced based on configuration
        public: false

    allegro_redis_odm.document_manager:
        class: Phillarmonic\AllegroRedisOdmBundle\DocumentManager
        arguments:
            - '@allegro_redis_odm.client_adapter'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.hydrator'
        public: true

    allegro_redis_odm.metadata_factory:
        class: Phillarmonic\AllegroRedisOdmBundle\Mapping\MetadataFactory
        arguments:
            - '@parameter_bag'  # Pass the entire parameter bag instead of just the mappings
        public: true

    # Added MappingDebugger service
    allegro_redis_odm.mapping_debugger:
        class: Phillarmonic\AllegroRedisOdmBundle\Service\MappingDebuggerService
        arguments:
            - '@allegro_redis_odm.metadata_factory'
            - '@service_container'
        public: true

    # Aliasing the service for autowiring
    Phillarmonic\AllegroRedisOdmBundle\Service\MappingDebuggerService:
        alias: 'allegro_redis_odm.mapping_debugger'
        public: true

    allegro_redis_odm.hydrator:
        class: Phillarmonic\AllegroRedisOdmBundle\Hydrator\Hydrator
        arguments:
            - '@allegro_redis_odm.metadata_factory'
        public: false

    allegro_redis_odm.repository_factory:
        class: Phillarmonic\AllegroRedisOdmBundle\Repository\RepositoryFactory
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
        public: false

    # Import mapping attributes as services
    Phillarmonic\AllegroRedisOdmBundle\Mapping\:
        resource: '../../Mapping/*'
        exclude: '../../Mapping/{ClassMetadata.php}'

    Phillarmonic\AllegroRedisOdmBundle\Command\:
        resource: '../../Command/*'
        tags: [ 'console.command' ]

    Phillarmonic\AllegroRedisOdmBundle\Command\DebugMappingsCommand:
        arguments:
            - '@allegro_redis_odm.mapping_debugger'
            - '@allegro_redis_odm.metadata_factory'
        tags: [ 'console.command' ]

    Phillarmonic\AllegroRedisOdmBundle\Command\RebuildIndexesCommand:
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.mapping_debugger'
        tags: [ 'console.command' ]

    Phillarmonic\AllegroRedisOdmBundle\Command\PurgeIndexesCommand:
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.mapping_debugger'
        tags: [ 'console.command' ]