services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Public services
    Phillarmonic\AllegroRedisOdmBundle\DocumentManager:
        alias: 'allegro_redis_odm.document_manager'
        public: true

    # The Redis client will be configured by the extension based on configuration
    allegro_redis_odm.client:
        class: Redis  # This will be replaced based on configuration
        public: false

    allegro_redis_odm.document_manager:
        class: Phillarmonic\AllegroRedisOdmBundle\DocumentManager
        arguments:
            - '@allegro_redis_odm.client_adapter'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.hydrator'
        public: true

    allegro_redis_odm.metadata_factory:
        class: Phillarmonic\AllegroRedisOdmBundle\Mapping\MetadataFactory
        arguments:
            - '@parameter_bag'  # Pass the entire parameter bag
        public: true

    allegro_redis_odm.mapping_debugger:
        class: Phillarmonic\AllegroRedisOdmBundle\Service\MappingDebuggerService
        arguments:
            - '@allegro_redis_odm.metadata_factory'
            - '@service_container'
        public: true

    Phillarmonic\AllegroRedisOdmBundle\Service\MappingDebuggerService:
        alias: 'allegro_redis_odm.mapping_debugger'
        public: true

    allegro_redis_odm.hydrator:
        class: Phillarmonic\AllegroRedisOdmBundle\Hydrator\Hydrator
        arguments:
            - '@allegro_redis_odm.metadata_factory'
        public: false

    allegro_redis_odm.repository_factory:
        class: Phillarmonic\AllegroRedisOdmBundle\Repository\RepositoryFactory
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
        public: false

    allegro_redis_odm.batch_processor:
        class: Phillarmonic\AllegroRedisOdmBundle\Service\BatchProcessor
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - 100  # Default batch size
        public: true

    Phillarmonic\AllegroRedisOdmBundle\Service\BatchProcessor:
        alias: 'allegro_redis_odm.batch_processor'
        public: true

    allegro_redis_odm.bulk_operations:
        class: Phillarmonic\AllegroRedisOdmBundle\Service\BulkOperations
        arguments:
            - '@allegro_redis_odm.client_adapter'
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.batch_processor'
        public: true

    Phillarmonic\AllegroRedisOdmBundle\Service\BulkOperations:
        alias: 'allegro_redis_odm.bulk_operations'
        public: true

    # Import mapping attributes as services
    Phillarmonic\AllegroRedisOdmBundle\Mapping\:
        resource: '../../Mapping/*'
        exclude: '../../Mapping/{ClassMetadata.php}'

    # Auto-register all commands in the Command directory
    Phillarmonic\AllegroRedisOdmBundle\Command\:
        resource: '../../Command/*'
        tags: [ 'console.command' ]

    # Explicit definitions for commands to ensure correct argument wiring
    # (though autowiring might handle these, explicit is often clearer)

    Phillarmonic\AllegroRedisOdmBundle\Command\DebugMappingsCommand:
        arguments:
            - '@allegro_redis_odm.mapping_debugger'
            - '@allegro_redis_odm.metadata_factory'
        tags: [ 'console.command' ]

    Phillarmonic\AllegroRedisOdmBundle\Command\RebuildIndexesCommand:
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.mapping_debugger'
        tags: [ 'console.command' ]

    Phillarmonic\AllegroRedisOdmBundle\Command\PurgeIndexesCommand:
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.mapping_debugger'
        tags: [ 'console.command' ]

    Phillarmonic\AllegroRedisOdmBundle\Command\AnalyzePerformanceCommand:
        arguments:
            - '@allegro_redis_odm.document_manager'
            - '@allegro_redis_odm.metadata_factory'
            - '@allegro_redis_odm.mapping_debugger'
            - '@allegro_redis_odm.bulk_operations'
        tags: [ 'console.command' ]